In [2]:
import pandas as pd

dataset = pd.read_csv("../data/fake_or_real_news.csv")
dataset.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [7]:
dataset_clean = dataset[["title", "label"]].rename(columns={"title": "text"})

dataset_clean["label"] = dataset_clean["label"].str.upper().map({"REAL": 1, "FAKE": 0})

dataset_clean = dataset_clean.dropna(subset=["text", "label"])

dataset_clean["text"] = dataset_clean["text"].astype(str).str.strip()

dataset_clean = dataset_clean[dataset_clean["text"] != ""]

dataset_clean = dataset_clean.drop_duplicates(subset=["text"]).reset_index()

nb_titres_par_classe = dataset_clean["label"].value_counts().sort_index()

proportion_par_classe = dataset_clean["label"].value_counts().sort_index()

text_len_words = dataset_clean["text"].str.split().str.len()

longueur_moyenne_totale = text_len_words.mean()

longueur_moyenne_par_classe = dataset_clean.assign(text_len_words=text_len_words).groupby("label")["text_len_words"].mean().sort_index()

print("titres par classe")
print(nb_titres_par_classe)

print("porportion par classe")
print(proportion_par_classe)

print("longueur moyenne totale")
print(longueur_moyenne_totale)

print("longueur moyenne par classe")
print(longueur_moyenne_par_classe)

dataset_clean.to_csv("../data/titles_clean.csv", index=False) #on save

dataset_clean.head()

titres par classe
label
0    3107
1    3149
Name: count, dtype: int64
porportion par classe
label
0    3107
1    3149
Name: count, dtype: int64
longueur moyenne totale
10.500479539641944
longueur moyenne par classe
label
0    11.138719
1     9.870753
Name: text_len_words, dtype: float64

   index                                               text  label
0      0                       You Can Smell Hillary’s Fear      0
1      1  Watch The Exact Moment Paul Ryan Committed Pol...      0
2      2        Kerry to go to Paris in gesture of sympathy      1
3      3  Bernie supporters on Twitter erupt in anger ag...      0
4      4   The Battle of New York: Why This Primary Matters      1

Le code semble correctement équilibré.